//! Generates the virtual `@local/quillmark-helper:0.1.0` package that provides
//! document data to Typst plates.
//!
//! `lib.typ` is regenerated per render as pure source text: no runtime data
//! processing. What each schema node lowers to, and why the date closures
//! behind `display` are keyed by schema address instead of carried on the
//! value: `prose/canon/PLATE_DATA.md`.
//!
//! Output is **canonical**: dict keys emit in sorted order at every level (via
//! [`sorted`]), so equal data produces byte-equal source regardless of the
//! caller's field order. `$cards` array order is semantic and preserved. A node
//! whose *schema* fixes a key order says so with `quillmark:order` and gets it
//! ([`ordered`]); that order is a property of the schema, so byte-equality holds
//! there too.

use std::collections::HashMap;
use std::ops::Range;

use crate::emit::{
    emit_content, emit_content_inline, escape_string, EmitError, Emission, SegmentMap,
};
use crate::SchemaMeta;
use quillmark_content::serial::from_canonical_value;
use quillmark_core::quill::{CONTENT_MEDIA_TYPE, QUILLMARK_INLINE_KEY, QUILLMARK_ORDER_KEY};

pub const HELPER_VERSION: &str = "0.1.0";
pub const HELPER_NAMESPACE: &str = "local";
pub const HELPER_NAME: &str = "quillmark-helper";

const LIB_TYP_TEMPLATE: &str = include_str!("lib.typ.template");

/// One generated content block's source map in the produced `lib.typ`: the
/// bracketed `block` range (brackets included) plus the emitter's
/// [`SegmentMap`]s, rebased so every `generated` range indexes `lib.typ`
/// directly. Every glyph the block places carries a span resolving into `block`.
#[derive(Debug)]
pub struct ContentMap {
    pub path: String,
    pub block: Range<usize>,
    pub segments: Vec<SegmentMap>,
    /// [`Emission::declined_images`] for this block.
    pub declined_images: usize,
}

/// The source plus each content block's [`ContentMap`]. `Err` only when a
/// content exceeds the nesting bound, which import already caps.
pub fn generate_lib_typ(
    data: &serde_json::Value,
    meta: &SchemaMeta,
) -> Result<(String, Vec<ContentMap>), EmitError> {
    let mut cg = Codegen::new(meta);
    let empty = serde_json::Map::new();
    let data_obj = data.as_object().unwrap_or(&empty);
    let data_literal = cg.emit_data(data_obj);
    // The recursive walk returns infallibly and records its failure here.
    if let Some(e) = cg.emit_error.take() {
        return Err(e);
    }
    let display_literal = display_literal(&cg.display);

    // Placeholders are located in the *raw template* (trusted static text), never
    // in already-substituted output, so document data spelling a placeholder
    // cannot hijack a splice point.
    let mut out = String::with_capacity(
        LIB_TYP_TEMPLATE.len() + cg.blocks.len() + data_literal.src.len() + display_literal.len(),
    );
    let mut cursor = 0usize;
    let mut blocks_at = 0usize;
    let mut data_at = 0usize;
    for (slot, value) in [
        ("{version}", HELPER_VERSION),
        ("{meta_literal}", meta.meta_literal()),
        ("{content_blocks}", cg.blocks.as_str()),
        ("{data_literal}", data_literal.src.as_str()),
        ("{display_literal}", display_literal.as_str()),
    ] {
        let rel = LIB_TYP_TEMPLATE[cursor..]
            .find(slot)
            .unwrap_or_else(|| panic!("lib.typ.template carries the {slot} slot in order"));
        let at = cursor + rel;
        out.push_str(&LIB_TYP_TEMPLATE[cursor..at]);
        match slot {
            "{content_blocks}" => blocks_at = out.len(),
            "{data_literal}" => data_at = out.len(),
            _ => {}
        }
        out.push_str(value);
        cursor = at + slot.len();
    }
    out.push_str(&LIB_TYP_TEMPLATE[cursor..]);

    // Rebase every recorded window from section-relative to `lib.typ`-relative.
    let mut windows: Vec<ContentMap> = cg
        .windows
        .into_iter()
        .map(|(path, block, segments, declined_images)| ContentMap {
            path,
            block: (block.start + blocks_at)..(block.end + blocks_at),
            segments: segments
                .into_iter()
                .map(|s| rebase_segment(s, blocks_at))
                .collect(),
            declined_images,
        })
        .collect();
    windows.extend(data_literal.windows.into_iter().map(|(path, block)| ContentMap {
        path,
        block: (block.start + data_at)..(block.end + data_at),
        segments: Vec::new(),
        declined_images: 0,
    }));
    Ok((out, windows))
}

/// Shifts generated byte offsets only; content (USV) offsets are unaffected.
fn rebase_segment(mut s: SegmentMap, shift: usize) -> SegmentMap {
    s.generated = (s.generated.start + shift)..(s.generated.end + shift);
    for run in &mut s.runs {
        run.1 = (run.1.start + shift)..(run.1.end + shift);
    }
    s
}

/// Accumulates the generated helper across one render.
struct Codegen<'m> {
    meta: &'m SchemaMeta,
    blocks: String,
    windows: Vec<(String, Range<usize>, Vec<SegmentMap>, usize)>,
    counter: usize,
    emit_error: Option<EmitError>,
    /// `(schema address, block binding)` per present date. Backs `_qm-display`.
    display: Vec<(String, String)>,
}

impl<'m> Codegen<'m> {
    fn new(meta: &'m SchemaMeta) -> Self {
        Self {
            meta,
            blocks: String::new(),
            windows: Vec::new(),
            counter: 0,
            emit_error: None,
            display: Vec::new(),
        }
    }

    /// Binds `ec` as a `#let _qm_cN = [\n{markup}\n]` block. The `\n` wrap opens
    /// the block at a line boundary so line-anchored markup parses. Windows are
    /// recorded in `self.blocks` coordinates; `generate_lib_typ` shifts them
    /// once more by the block section's start.
    fn content_block(&mut self, path: &str, ec: Emission) -> String {
        let id = format!("_qm_c{}", self.counter);
        self.counter += 1;
        let declined_images = ec.declined_images;
        self.blocks.push_str("#let ");
        self.blocks.push_str(&id);
        self.blocks.push_str(" = ");
        let start = self.blocks.len();
        self.blocks.push_str("[\n");
        // The emitter's `generated` offsets are relative to the markup body,
        // which opens after `[\n`.
        let markup_at = self.blocks.len();
        self.blocks.push_str(&ec.markup);
        self.blocks.push_str("\n]");
        let end = self.blocks.len();
        self.blocks.push('\n');
        let segments = ec
            .segments
            .into_iter()
            .map(|s| rebase_segment(s, markup_at))
            .collect();
        self.windows
            .push((path.to_string(), start..end, segments, declined_images));
        id
    }

    /// The date sibling of [`content_block`](Self::content_block): a closure
    /// whose `text(..)` body is where the glyphs are born, so they carry this
    /// generated span wherever the plate finally calls it, which is what
    /// `display(addr, ..)` survives laundering on.
    fn display_block(&mut self, path: &str, constructor: &str) -> String {
        let id = format!("_qm_d{}", self.display.len());
        self.blocks.push_str("#let ");
        self.blocks.push_str(&id);
        self.blocks.push_str(" = (..args) => ");
        // The window covers exactly the `text(..)` call: the node whose span the
        // produced glyphs carry.
        let text_start = self.blocks.len();
        self.blocks.push_str("text(");
        self.blocks.push_str(constructor);
        self.blocks.push_str(".display(..args))");
        let text_end = self.blocks.len();
        self.blocks.push('\n');
        self.windows
            .push((path.to_string(), text_start..text_end, Vec::new(), 0));
        self.display.push((path.to_string(), id.clone()));
        id
    }

    /// The native cell and its `_qm_dN` closure. Blank ⇒ `none` and no
    /// closure, so a plate's `!= none` guard is untouched. A non-blank value
    /// that will not parse raises `backend::invalid_date` from here, the one
    /// site that parses, which is what makes the check total over depth.
    fn date_field(&mut self, path: &str, s: &str, kind: DateKind) -> (String, Option<String>) {
        match datetime_constructor(s, kind) {
            Some(constructor) => {
                let closure = self.display_block(path, &constructor);
                (constructor, Some(closure))
            }
            None if s.is_empty() => ("none".to_string(), None),
            None => {
                self.emit_error.get_or_insert(EmitError::InvalidDate {
                    field: path.to_string(),
                    value: s.to_string(),
                });
                ("none".to_string(), None)
            }
        }
    }

    /// A blank content lowers to `""`, not a block; a value that is not a valid
    /// content (never produced by the seam) degrades to its value literal.
    fn content_field(&mut self, path: &str, value: &serde_json::Value, inline: bool) -> String {
        let emit = if inline {
            emit_content_inline
        } else {
            emit_content
        };
        match from_canonical_value(value) {
            Ok(rt) if !rt.is_blank() => {
                match emit(&rt) {
                    Ok(ec) => self.content_block(path, ec),
                    Err(e) => {
                        self.emit_error.get_or_insert(e);
                        "\"\"".to_string()
                    }
                }
            }
            Ok(_) => "\"\"".to_string(),
            Err(_) => lit(value),
        }
    }

    fn emit_data(&mut self, obj: &serde_json::Map<String, serde_json::Value>) -> Frag {
        let mut dict = Container::default();
        for (key, value) in sorted(obj) {
            if key == "$cards" {
                if let Some(cards) = value.as_array() {
                    dict.items.push(entry(key, self.emit_cards(cards)));
                    continue;
                }
            }
            let node = self.meta.field_node(key);
            dict.push(key, self.emit_value(key, node, value));
        }
        dict.finish(Some(""))
    }

    /// A card with no string `$kind` passes through as a value literal, assigned
    /// no ordinal or `$path`.
    fn emit_cards(&mut self, cards: &[serde_json::Value]) -> Frag {
        let mut ordinals: HashMap<String, usize> = HashMap::new();
        let mut out = Vec::with_capacity(cards.len());
        for card in cards {
            let obj = match card.as_object() {
                Some(o) => o,
                None => {
                    out.push(Frag::from(lit(card)));
                    continue;
                }
            };
            match obj.get("$kind").and_then(|v| v.as_str()) {
                Some(kind) => {
                    let n = ordinals.entry(kind.to_string()).or_insert(0);
                    let prefix = format!("$cards.{kind}.{n}.");
                    *n += 1;
                    out.push(self.emit_card(obj, kind, &prefix));
                }
                None => out.push(Frag::from(lit(card))),
            }
        }
        Frag::wrap(out, "()")
    }

    fn emit_card(
        &mut self,
        obj: &serde_json::Map<String, serde_json::Value>,
        kind: &str,
        prefix: &str,
    ) -> Frag {
        let props = self.meta.card_props(kind);
        let mut dict = Container::default();
        // The canonical address prefix, so plates compose schema-field addresses
        // without reimplementing the kind+ordinal grammar.
        dict.items.push(Frag::from(format!("\"{PATH_KEY}\": \"{}\"", escape_string(prefix))));
        for (key, value) in sorted(obj) {
            let node = props.and_then(|p| p.get(key));
            dict.push(key, self.emit_value(&format!("{prefix}{key}"), node, value));
        }
        dict.finish(None)
    }

    /// Lower one value against the schema node that declares it, recursing on
    /// shape, into its data expression and, where [`inks`] holds for the node,
    /// its ink. `path` is the value's schema address, so every generated
    /// projection keys on an address the recursion produced rather than one
    /// reassembled.
    ///
    /// A value whose shape contradicts its declaration reaches here through a
    /// direct `update`, never the seam, and falls to its literal with `none` ink.
    fn emit_value(
        &mut self,
        path: &str,
        node: Option<&serde_json::Value>,
        value: &serde_json::Value,
    ) -> (Frag, Option<Frag>) {
        let (expr, ink) = match (lowering(node), value) {
            (Lower::Content { inline }, serde_json::Value::Object(_)) => {
                let expr = self.content_field(path, value, inline);
                (Frag::from(expr.clone()), Some(Frag::from(expr)))
            }
            (Lower::Date(kind), serde_json::Value::String(s)) => {
                // Called with no pattern, the closure places the date's default
                // display; `display(dict, key, ..)` calls it with the plate's.
                let (expr, closure) = self.date_field(path, s, kind);
                let ink = closure.map_or_else(|| "none".to_string(), |c| format!("{c}()"));
                (Frag::from(expr), Some(Frag::from(ink)))
            }
            (Lower::Array(items), serde_json::Value::Array(elems)) => {
                let (exprs, elem_inks): (Vec<Frag>, Vec<Option<Frag>>) = elems
                    .iter()
                    .enumerate()
                    .map(|(i, elem)| self.emit_value(&format!("{path}.{i}"), items, elem))
                    .unzip();
                let ink = inks(items).then(|| {
                    Frag::wrap(
                        elem_inks
                            .into_iter()
                            .map(|i| i.unwrap_or_else(|| Frag::from("none")))
                            .collect(),
                        "()",
                    )
                });
                (Frag::wrap(exprs, "()"), ink)
            }
            (Lower::Object(props, order), serde_json::Value::Object(obj)) => {
                let mut dict = Container::default();
                for (key, elem) in ordered(obj, &order) {
                    let lowered = self.emit_value(&format!("{path}.{key}"), props.get(key), elem);
                    dict.push(key, lowered);
                }
                (dict.finish(Some(&format!("{path}."))), None)
            }
            (
                Lower::Native,
                serde_json::Value::String(_)
                | serde_json::Value::Number(_)
                | serde_json::Value::Bool(_),
            ) if node.is_some() => {
                // Parenthesized: a bare `#` embed will not lex a unary minus.
                let expr = lit(value);
                let ink = Frag::window(path, format!("[#({expr})]"));
                (Frag::from(expr), Some(ink))
            }
            _ => (Frag::from(lit(value)), None),
        };
        let ink = ink.or_else(|| inks(node).then(|| Frag::from("none")));
        (expr, ink)
    }
}

/// Whether a field declared by `node` has ink: every declared type a plate
/// prints, and an array of them. A container does not; it carries `$ink` of
/// its own.
fn inks(node: Option<&serde_json::Value>) -> bool {
    let Some(n) = node else {
        return false;
    };
    match lowering(node) {
        Lower::Content { .. } | Lower::Date(_) => true,
        Lower::Array(items) => inks(items),
        Lower::Object(..) => false,
        Lower::Native => node_type(n) != Some("object"),
    }
}

/// A span of generated source and the scalar ink windows inside it, as
/// `(schema address, byte range)` relative to the fragment's start. Composing
/// fragments shifts their windows, so the data literal knows where each of its
/// inline ink blocks lands without a second pass over the text.
#[derive(Default)]
struct Frag {
    src: String,
    windows: Vec<(String, Range<usize>)>,
}

impl From<String> for Frag {
    fn from(src: String) -> Self {
        Self {
            src,
            windows: Vec::new(),
        }
    }
}

impl From<&str> for Frag {
    fn from(src: &str) -> Self {
        Self::from(src.to_string())
    }
}

impl Frag {
    /// One ink block whose glyphs are born inside `src`, windowed whole.
    fn window(path: &str, src: String) -> Self {
        Self {
            windows: vec![(path.to_string(), 0..src.len())],
            src,
        }
    }

    fn push_str(&mut self, s: &str) {
        self.src.push_str(s);
    }

    fn append(&mut self, other: Frag) {
        let shift = self.src.len();
        self.src.push_str(&other.src);
        self.windows.extend(
            other
                .windows
                .into_iter()
                .map(|(path, r)| (path, (r.start + shift)..(r.end + shift))),
        );
    }

    /// [`wrap_array`] / [`wrap_dict`] over fragments; `empty` is the literal for
    /// no items.
    fn wrap(items: Vec<Frag>, empty: &str) -> Frag {
        if items.is_empty() {
            return Frag::from(empty);
        }
        let mut out = Frag::from("(");
        for (i, item) in items.into_iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.append(item);
        }
        out.push_str(",)");
        out
    }
}

/// `"key": value` as a dictionary item.
fn entry(key: &str, value: Frag) -> Frag {
    let mut out = Frag::from(format!("\"{}\": ", escape_string(key)));
    out.append(value);
    out
}

/// A dictionary under construction, with the `$ink` twin of its fields. A data
/// key spelling `$ink` or `$path` is dropped, so the generated one is the only
/// one.
#[derive(Default)]
struct Container {
    items: Vec<Frag>,
    ink: Vec<Frag>,
}

impl Container {
    fn push(&mut self, key: &str, (expr, ink): (Frag, Option<Frag>)) {
        if key == INK_KEY || key == PATH_KEY {
            return;
        }
        self.items.push(entry(key, expr));
        if let Some(ink) = ink {
            self.ink.push(entry(key, ink));
        }
    }

    /// `$ink` leads, then `path` as `$path` for `display(dict, key, ..)` to
    /// address a date by; both only where a field has ink, so a dictionary of
    /// containers (a `matrix`) keeps exactly its members as keys. The `{..}`
    /// code block is a unit Typst's incremental reparser swaps alone: an edit
    /// touches a field and its ink, and inside a card or a row the block
    /// holding both is that card or row, not the whole literal.
    fn finish(mut self, path: Option<&str>) -> Frag {
        if !self.ink.is_empty() {
            let ink = Frag::wrap(self.ink, "(:)");
            let mut head = vec![entry(INK_KEY, ink)];
            if let Some(path) = path {
                head.push(Frag::from(format!(
                    "\"{PATH_KEY}\": \"{}\"",
                    escape_string(path)
                )));
            }
            self.items.splice(0..0, head);
        }
        let mut out = Frag::from("{");
        out.append(Frag::wrap(self.items, "(:)"));
        out.push_str("}");
        out
    }
}

const INK_KEY: &str = "$ink";
const PATH_KEY: &str = "$path";

/// What a schema node lowers to: the codegen walk's whole dispatch. Why only
/// the content types lower to content and a date does not:
/// `prose/canon/PLATE_DATA.md`.
enum Lower<'a> {
    /// `richtext` / `plaintext`, which share everything downstream of this
    /// classification. `inline` lowers to pure inline markup, with no block
    /// terminator to warn inside a paragraph.
    Content { inline: bool },
    Date(DateKind),
    /// The element node, absent where an array declares no `items`.
    Array(Option<&'a serde_json::Value>),
    /// The declared members, and the key order the schema fixes for them
    /// (`quillmark:order`), empty where it fixes none.
    Object(&'a serde_json::Map<String, serde_json::Value>, Vec<&'a str>),
    /// Every other declared type, plus every data key the schema does not
    /// declare and every container declaring no members to recurse on.
    Native,
}

fn lowering(node: Option<&serde_json::Value>) -> Lower<'_> {
    let Some(node) = node else {
        return Lower::Native;
    };
    let str_key = |key: &str| node.get(key).and_then(|v| v.as_str());
    if str_key("contentMediaType") == Some(CONTENT_MEDIA_TYPE) {
        return Lower::Content {
            inline: node.get(QUILLMARK_INLINE_KEY).and_then(|v| v.as_bool()) == Some(true),
        };
    }
    match str_key("format") {
        Some("date") => return Lower::Date(DateKind::Date),
        Some("date-time") => return Lower::Date(DateKind::DateTime),
        _ => {}
    }
    match node_type(node) {
        Some("array") => Lower::Array(node.get("items")),
        // A richtext node is `type: object` too, and the media type claimed it
        // above.
        Some("object") => match node.get("properties").and_then(|v| v.as_object()) {
            Some(props) => Lower::Object(props, declared_order(node)),
            None => Lower::Native,
        },
        _ => Lower::Native,
    }
}

/// A node's declared type: its `type` string, or the non-`null` member of an
/// optional cell's `[<type>, "null"]` union.
pub(crate) fn node_type(node: &serde_json::Value) -> Option<&str> {
    match node.get("type")? {
        serde_json::Value::String(ty) => Some(ty),
        serde_json::Value::Array(union) => union
            .iter()
            .filter_map(|v| v.as_str())
            .find(|ty| *ty != "null"),
        _ => None,
    }
}

/// The two date field types, distinguished by their Typst `datetime(..)` arity.
#[derive(Clone, Copy)]
enum DateKind {
    Date,
    DateTime,
}

/// Each present date's `_qm_dN` closure keyed by schema address, backing the
/// `display(field, ..)` helper. Keys sort so a reorder-only `update` still
/// produces byte-identical source.
fn display_literal(entries: &[(String, String)]) -> String {
    let mut sorted: Vec<&(String, String)> = entries.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    wrap_dict(
        sorted
            .into_iter()
            .map(|(path, binding)| format!("\"{}\": {}", escape_string(path), binding))
            .collect(),
    )
}

/// `None` for a string that does not parse (the empty string included), which
/// the caller lowers to `none`. Reuses the coercion layer's own parse, so a
/// value that reached here parses and `None` is the defensive arm.
fn datetime_constructor(s: &str, kind: DateKind) -> Option<String> {
    match kind {
        DateKind::Date => quillmark_core::quill::parse_date(s)
            .map(|(year, month, day)| format!("datetime(year: {year}, month: {month}, day: {day})")),
        DateKind::DateTime => {
            quillmark_core::quill::parse_datetime(s).map(|(year, month, day, hour, minute, second)| {
                format!(
                    "datetime(year: {year}, month: {month}, day: {day}, \
                     hour: {hour}, minute: {minute}, second: {second})"
                )
            })
        }
    }
}

/// Serialize a JSON value as a Typst literal expression, mirroring the value
/// model `json()` produces: `null` ⇒ `none`; integral `i64` numbers ⇒ int
/// literals; all other numbers ⇒ `float("..")` (Typst float *literals* take no
/// exponent syntax, but the `float(str)` constructor parses every finite
/// `f64`, and `json()` rejects non-finite numbers); strings via
/// [`escape_string`]; arrays and objects via [`wrap_array`] / [`wrap_dict`].
pub(crate) fn lit(v: &serde_json::Value) -> String {
    use serde_json::Value::*;
    match v {
        Null => "none".to_string(),
        Bool(b) => b.to_string(),
        Number(n) => {
            if let Some(i) = n.as_i64() {
                // Typst lexes a negative literal as unary `-` over an unsigned
                // magnitude, and `i64::MIN`'s magnitude overflows i64, so it
                // would not round-trip as a literal.
                if i == i64::MIN {
                    "(-9223372036854775807 - 1)".to_string()
                } else {
                    i.to_string()
                }
            } else {
                let f = n.as_f64().expect("json numbers are finite");
                format!("float(\"{f}\")")
            }
        }
        String(s) => format!("\"{}\"", escape_string(s)),
        Array(a) => wrap_array(a.iter().map(lit).collect()),
        Object(o) => wrap_dict(
            sorted(o)
                .into_iter()
                .map(|(k, v)| format!("\"{}\": {}", escape_string(k), lit(v)))
                .collect(),
        ),
    }
}

/// The workspace builds `serde_json` with `preserve_order`, so a map's own
/// iteration order is the caller's. Sorting makes the generated source a pure
/// function of the data's *values*, so a reorder-only `update` produces
/// byte-identical `lib.typ` and comemo reuses the whole compile.
fn sorted(obj: &serde_json::Map<String, serde_json::Value>) -> Vec<(&String, &serde_json::Value)> {
    let mut entries: Vec<_> = obj.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    entries
}

/// The schema's declared key order for a container node, `[]` where it declares
/// none. A `matrix` declares one: its roster is the order a plate prints the
/// vocabulary in.
fn declared_order(node: &serde_json::Value) -> Vec<&str> {
    node.get(QUILLMARK_ORDER_KEY)
        .and_then(|v| v.as_array())
        .map(|ids| ids.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default()
}

/// `obj`'s entries in the schema's declared order where it declares one, keys it
/// does not name trailing in sorted order; [`sorted`] otherwise.
///
/// The order comes from the schema, never from the data, so the generated source
/// stays a pure function of the data's values and comemo's reuse is untouched.
fn ordered<'a>(
    obj: &'a serde_json::Map<String, serde_json::Value>,
    order: &[&str],
) -> Vec<(&'a String, &'a serde_json::Value)> {
    if order.is_empty() {
        return sorted(obj);
    }
    let mut entries: Vec<(&String, &serde_json::Value)> = order
        .iter()
        .filter_map(|id| obj.get_key_value(*id))
        .collect();
    entries.extend(sorted(obj).into_iter().filter(|(k, _)| !order.contains(&k.as_str())));
    entries
}

/// The trailing comma keeps a single element an array rather than a
/// parenthesized scalar.
fn wrap_array(items: Vec<String>) -> String {
    if items.is_empty() {
        "()".to_string()
    } else {
        format!("({},)", items.join(", "))
    }
}

fn wrap_dict(items: Vec<String>) -> String {
    if items.is_empty() {
        "(:)".to_string()
    } else {
        format!("({},)", items.join(", "))
    }
}

pub fn generate_typst_toml() -> String {
    format!(
        r#"[package]
name = "{name}"
version = "{version}"
namespace = "{namespace}"
entrypoint = "lib.typ"
"#,
        name = HELPER_NAME,
        version = HELPER_VERSION,
        namespace = HELPER_NAMESPACE
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::emit::escape_markup;
    use crate::emit::EscapeCtx;
    use quillmark_core::quill::CONTENT_MEDIA_TYPE;

    fn meta_from(schema: serde_json::Value) -> SchemaMeta {
        SchemaMeta::from_schema_json(&schema)
    }

    fn content(markdown: &str) -> serde_json::Value {
        let rt = quillmark_content::import::from_markdown(markdown).expect("import");
        quillmark_content::serial::to_canonical_value(&rt)
    }

    fn richtext_field() -> serde_json::Value {
        serde_json::json!({ "type": "object", "contentMediaType": CONTENT_MEDIA_TYPE })
    }

    fn inline_richtext_field() -> serde_json::Value {
        serde_json::json!({
            "type": "object",
            "contentMediaType": CONTENT_MEDIA_TYPE,
            "quillmark:inline": true
        })
    }

    #[test]
    fn inline_field_lowers_without_parbreak() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "subject": inline_richtext_field(),
            "intro": richtext_field(),
        }}));
        let data = serde_json::json!({
            "subject": content("A **bold** subject"),
            "intro": content("An intro."),
        });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        assert!(
            lib.contains("[\nA #strong[bold] subject\n]"),
            "inline block should carry no parbreak: {lib}"
        );
        assert!(
            lib.contains("[\nAn intro.\n\n\n]"),
            "block field keeps its terminator: {lib}"
        );
    }

    /// The `quillmark:inline` flag sits on `items` for an array field.
    #[test]
    fn inline_array_lowers_each_element_without_parbreak() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "cc": { "type": "array", "items": inline_richtext_field() }
        }}));
        let data = serde_json::json!({ "cc": [content("First"), content("Second **bold**")] });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        assert!(lib.contains("[\nFirst\n]"), "{lib}");
        assert!(lib.contains("[\nSecond #strong[bold]\n]"), "{lib}");
    }

    #[test]
    fn content_field_becomes_a_referenced_block_with_a_bracket_window() {
        let meta = meta_from(serde_json::json!({ "properties": { "intro": richtext_field() } }));
        let data = serde_json::json!({ "intro": content("A **bold** intro.") });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        let block = "[\nA #strong[bold] intro.\n\n\n]";
        assert!(lib.contains(&format!("#let _qm_c0 = {block}")));
        assert!(lib.contains("\"intro\": _qm_c0"));
        // No eval, no json() blob, no runtime assembly survive.
        assert!(!lib.contains("eval("));
        assert!(!lib.contains("json(bytes"));
        assert!(!lib.contains("insert-content"));
        assert!(!lib.contains("_parse-date"));

        assert_eq!(windows.len(), 1);
        assert_eq!(windows[0].path, "intro");
        assert_eq!(&lib[windows[0].block.clone()], block);
    }

    /// The source map must be byte-accurate against the emitted `lib.typ`, not
    /// just against the emitter's own markup.
    #[test]
    fn segment_maps_index_the_generated_lib_typ() {
        let meta = meta_from(serde_json::json!({ "properties": { "intro": richtext_field() } }));
        let rt = quillmark_content::import::from_markdown("Hello **bold**.\n\nSecond para.")
            .expect("import");
        let data =
            serde_json::json!({ "intro": quillmark_content::serial::to_canonical_value(&rt) });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        assert_eq!(windows.len(), 1);
        let cm = &windows[0];
        assert_eq!(cm.segments.len(), 2);
        let chars: Vec<char> = rt.text.chars().collect();
        let mut saw_bold = false;
        for seg in &cm.segments {
            assert!(seg.generated.start <= seg.generated.end && seg.generated.end <= lib.len());
            for (content_range, generated, ctx) in &seg.runs {
                let src: String = chars[content_range.clone()].iter().collect();
                let expect = match ctx {
                    EscapeCtx::Markup => escape_markup(&src),
                    EscapeCtx::StringLit => crate::emit::escape_string(&src),
                };
                assert_eq!(&lib[generated.clone()], expect, "run inverts to its content slice");
                assert!(generated.start >= seg.generated.start && generated.end <= seg.generated.end);
                if src == "bold" {
                    saw_bold = true;
                }
            }
        }
        assert!(saw_bold, "the strong-wrapped run maps back to \"bold\"");
    }

    #[test]
    fn richtext_array_emits_a_block_per_nonblank_element() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "sections": {
                    "type": "array",
                    "items": richtext_field()
                }
            }
        }));
        let data = serde_json::json!({
            "sections": [content("one"), content(""), content("three")]
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert_eq!(paths, vec!["sections.0", "sections.2"]);
        assert!(lib.contains("\"sections\": (_qm_c0, \"\", _qm_c1,)"));
    }

    #[test]
    fn date_fields_lower_to_native_datetimes_beside_a_display_projection() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "issued": { "type": "string", "format": "date" },
                "at": { "type": "string", "format": "date-time" },
                "signed": { "type": "string", "format": "date" }
            }
        }));
        let data = serde_json::json!({
            "issued": "2026-07-03",
            "at": "2026-07-03T09:30",
            "signed": null
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();
        // The data cell is the constructor itself: `data.issued.year()` and
        // `data.issued < data.at` are ordinary Typst.
        assert!(
            lib.contains("\"issued\": datetime(year: 2026, month: 7, day: 3)"),
            "{lib}"
        );
        assert!(
            lib.contains(
                "\"at\": datetime(year: 2026, month: 7, day: 3, hour: 9, minute: 30, second: 0)"
            ),
            "{lib}"
        );
        assert!(lib.contains("\"signed\": none"), "{lib}");

        // Keys emit in sorted order, so `_qm_d0` is `at` and `_qm_d1` `issued`.
        assert!(
            lib.contains("#let _qm_d1 = (..args) => text(datetime(year: 2026, month: 7, day: 3).display(..args))"),
            "{lib}"
        );
        assert!(
            lib.contains(r#"("at": _qm_d0, "issued": _qm_d1,)"#),
            "the display table keys by schema address: {lib}"
        );
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert!(paths.contains(&"issued"), "{paths:?}");
        assert!(paths.contains(&"at"), "{paths:?}");
        assert!(!paths.contains(&"signed"), "{paths:?}");
    }

    /// Every nested position the one-level nesting contract admits, for both
    /// rich types.
    #[test]
    fn nested_dates_and_content_lower_exactly_as_card_level_ones_do() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "stamps": { "type": "array", "items": { "type": "string", "format": "date" } },
            "contact": { "type": "object", "properties": {
                "reply_by": { "type": "string", "format": "date" },
                "note": richtext_field(),
            }},
            "rows": { "type": "array", "items": { "type": "object", "properties": {
                "on": { "type": "string", "format": "date" },
                "notes": richtext_field(),
            }}},
        }}));
        let data = serde_json::json!({
            "stamps": ["2026-01-02"],
            "contact": { "reply_by": "2026-03-04", "note": content("a **nested** note") },
            "rows": [{ "on": "2026-05-06", "notes": content("row _one_") }],
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        assert!(
            lib.contains("\"stamps\": (datetime(year: 2026, month: 1, day: 2),)"),
            "an array element is a date: {lib}"
        );
        assert!(
            lib.contains("\"reply_by\": datetime(year: 2026, month: 3, day: 4)"),
            "an object property is a date: {lib}"
        );
        assert!(
            lib.contains("\"on\": datetime(year: 2026, month: 5, day: 6)"),
            "a typed-table row property is a date: {lib}"
        );
        assert!(
            lib.contains("[\na #strong[nested] note\n\n\n]"),
            "an object's content property is a markup block: {lib}"
        );
        assert!(
            lib.contains("[\nrow #emph[one]\n\n\n]"),
            "a row's content property is a markup block: {lib}"
        );
        // No canonical-content wire JSON survives anywhere in the data literal.
        assert!(!lib.contains("\"lines\""), "wire JSON leaked: {lib}");

        // Every projection keys on the address the recursion produced.
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        for expected in ["stamps.0", "contact.reply_by", "contact.note", "rows.0.on", "rows.0.notes"] {
            assert!(paths.contains(&expected), "missing {expected}: {paths:?}");
        }
    }

    /// A bad date must fail loudly at any depth, and must keep its code: a
    /// silent blank would ship a document dated wrong.
    #[test]
    fn an_unparseable_nested_date_is_a_coded_render_error() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "contact": { "type": "object", "properties": {
                "reply_by": { "type": "string", "format": "date" },
            }},
        }}));
        let data = serde_json::json!({ "contact": { "reply_by": "not-a-date" } });
        let err = generate_lib_typ(&data, &meta).expect_err("a bad date stops codegen");
        assert_eq!(err.code(), "backend::invalid_date");
        assert!(err.to_string().contains("contact.reply_by"), "{err}");

        // A blank stays `none`, so a plate's `!= none` guard is untouched.
        let blank = serde_json::json!({ "contact": { "reply_by": "" } });
        let (lib, _) = generate_lib_typ(&blank, &meta).unwrap();
        assert!(lib.contains("\"reply_by\": none"), "{lib}");
    }

    #[test]
    fn cards_carry_path_and_per_kind_ordinals() {
        let meta = meta_from(serde_json::json!({
            "properties": {},
            "$defs": {
                "note_card": {
                    "properties": {
                        "$body": richtext_field(),
                        "on": { "type": "string", "format": "date" }
                    }
                }
            }
        }));
        let data = serde_json::json!({
            "$cards": [
                { "$kind": "note", "$body": content("First body"), "on": "2026-01-02" },
                { "$kind": "note", "$body": content("Second body") }
            ]
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();
        // Each instance gets its own windows, keyed by the card's full address.
        let paths: Vec<&str> = windows.iter().map(|w| w.path.as_str()).collect();
        assert!(paths.contains(&"$cards.note.0.$body"), "{paths:?}");
        assert!(paths.contains(&"$cards.note.1.$body"), "{paths:?}");
        assert!(paths.contains(&"$cards.note.0.on"), "{paths:?}");
        assert!(lib.contains("\"$path\": \"$cards.note.0.\""));
        assert!(lib.contains("\"$path\": \"$cards.note.1.\""));
        assert!(
            lib.contains("\"on\": datetime(year: 2026, month: 1, day: 2)"),
            "{lib}"
        );
        assert!(
            lib.contains(r#"("$cards.note.0.on": _qm_d0,)"#),
            "a card date's display projection keys on its per-instance address: {lib}"
        );
    }

    /// Each printable field's ink sits beside it under `$ink` with the
    /// dictionary's `$path`, a blank's is `none`, a date's calls its closure, a
    /// dictionary of dictionaries carries neither, and every scalar ink block
    /// is windowed on the address it prints.
    #[test]
    fn ink_twins_each_printable_field_and_windows_its_scalars() {
        let meta = meta_from(serde_json::json!({ "properties": {
            "subject": { "type": "string" },
            "count": { "type": "integer" },
            "due": { "type": ["string", "null"], "format": "date" },
            "on": { "type": "string", "format": "date" },
            "tags": { "type": "array", "items": { "type": "string" } },
            "rows": { "type": "array", "items": { "type": "object", "properties": {
                "org": { "type": "string" },
            }}},
            "grid": { "type": "object", "properties": {
                "a": { "type": "object", "properties": { "x": { "type": "string" } } },
            }},
        }}));
        let data = serde_json::json!({
            "subject": "Widgets",
            "count": 3,
            "due": null,
            "on": "2026-01-02",
            "tags": [],
            "rows": [{ "org": "AFRL", "$ink": "spoofed", "$path": "spoofed" }],
            "grid": { "a": { "x": "1" } },
        });
        let (lib, windows) = generate_lib_typ(&data, &meta).unwrap();

        assert!(
            lib.contains(
                r#"#let data = {("$ink": ("count": [#(3)], "due": none, "on": _qm_d0(), "subject": [#("Widgets")], "tags": (),), "$path": "", "count": 3,"#
            ),
            "{lib}"
        );
        assert!(
            lib.contains(r#""rows": ({("$ink": ("org": [#("AFRL")],), "$path": "rows.0.", "org": "AFRL",)},)"#),
            "a row carries its own ink and path, and data keys spelling them are dropped: {lib}"
        );
        assert!(
            lib.contains(r#""grid": {("a": {("$ink": ("x": [#("1")],), "$path": "grid.a.", "x": "1",)},)}"#),
            "{lib}"
        );

        let scalars: Vec<(&str, &str)> = windows
            .iter()
            .map(|w| (w.path.as_str(), &lib[w.block.clone()]))
            .collect();
        for expected in [
            ("count", "[#(3)]"),
            ("subject", r#"[#("Widgets")]"#),
            ("rows.0.org", r#"[#("AFRL")]"#),
            ("grid.a.x", r#"[#("1")]"#),
        ] {
            assert!(scalars.contains(&expected), "{expected:?} in {scalars:?}");
        }
    }

    #[test]
    fn meta_literal_carries_the_address_tables() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "subject": { "type": "string" },
                "refs": { "type": "array", "items": { "type": "string" } }
            }
        }));
        let (lib, _) = generate_lib_typ(&serde_json::json!({}), &meta).unwrap();
        assert!(lib.contains("#let _qm-meta = ("));
        // A scalar is a leaf, and a primitive-element array offers its index
        // step onto one: neither carries a `props` entry.
        assert!(
            lib.contains("\"props\": (\"refs\": (\"item\": (:),), \"subject\": (:),)"),
            "{lib}"
        );
    }

    /// `array_fields` and `object_fields` are one shape, so one predicate reads
    /// both steps.
    #[test]
    fn a_typed_table_row_publishes_its_property_names() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "tags": { "type": "array", "items": { "type": "string" } },
                "refs": { "type": "array", "items": { "type": "object", "properties": {
                    "org": { "type": "string" },
                    "num": { "type": "string" },
                }}},
            }
        }));
        // A primitive-element array offers the index step and nothing past it.
        let tags = meta.root.resolve("tags.0").expect("tags.0");
        assert!(tags.props.is_empty() && tags.item.is_none());
        assert_eq!(
            meta.root
                .resolve("refs.0")
                .expect("refs.0")
                .props
                .keys()
                .cloned()
                .collect::<Vec<_>>(),
            vec!["num".to_string(), "org".to_string()],
        );
    }

    /// A variant container's cells reach the table a typed dictionary's do,
    /// and a richtext field stays out of it, offering no property step.
    #[test]
    fn object_fields_table_carries_every_declared_container() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "subject": { "type": "string" },
                "body": richtext_field(),
                "address": { "type": "object", "properties": {
                    "city": { "type": "string" },
                }},
                "classification": { "type": "object", "properties": {
                    "value": { "type": "string", "enum": ["", "CUI"] },
                    "poc": { "type": "string" },
                }},
            },
            "$defs": { "note_card": { "properties": {
                "origin": { "type": "object", "properties": { "office": { "type": "string" } } },
            }}}
        }));
        assert!(meta.root.resolve("address.city").is_some());
        assert!(meta.root.resolve("classification.value").is_some());
        assert!(meta.root.resolve("classification.poc").is_some());
        // A scalar and a richtext field each offer no step.
        assert!(meta.root.resolve("subject.anything").is_none());
        assert!(meta.root.resolve("body.text").is_none());
        assert!(meta.cards["note"].resolve("origin.office").is_some());

        let (lib, _) = generate_lib_typ(&serde_json::json!({}), &meta).unwrap();
        assert!(
            lib.contains("\"cards\": (\"note\": (\"props\": (\"origin\": (\"props\": (\"office\": (:),),),),),)"),
            "{lib}"
        );
    }

    /// A richtext field is `type: object` and would answer the object arm, so
    /// the media type must claim it first — otherwise its wire JSON walks as a
    /// dictionary and reaches the plate as raw canonical content.
    #[test]
    fn a_content_node_is_classified_before_the_object_arm() {
        assert!(matches!(
            lowering(Some(&richtext_field())),
            Lower::Content { inline: false }
        ));
        assert!(matches!(
            lowering(Some(&inline_richtext_field())),
            Lower::Content { inline: true }
        ));
        // An undeclared data key and a scalar take the same arm.
        assert!(matches!(lowering(None), Lower::Native));
        assert!(matches!(
            lowering(Some(&serde_json::json!({ "type": "string" }))),
            Lower::Native
        ));
    }

    /// Slots are located in the raw template only.
    #[test]
    fn data_containing_placeholder_text_cannot_hijack_the_splice() {
        let meta = SchemaMeta::default();
        let data = serde_json::json!({
            "note": "quoting the template: {content_blocks} and {data_literal}"
        });
        let (lib, _) = generate_lib_typ(&data, &meta).unwrap();
        let payload = lib.find("quoting the template").expect("payload present");
        let data_binding = lib.find("#let data =").expect("data binding present");
        assert!(
            payload > data_binding,
            "the payload sits inside the data literal, after the real slot"
        );
    }

    /// A reorder-only `update` must be a `Source::replace` no-op.
    #[test]
    fn reordered_input_emits_byte_identical_source() {
        let meta = meta_from(serde_json::json!({
            "properties": {
                "body": richtext_field(),
                "note": richtext_field(),
                "issued": { "type": "string", "format": "date" },
                "extra": { "type": "object" }
            },
            "$defs": {
                "note_card": {
                    "properties": {
                        "$body": richtext_field(),
                        "on": { "type": "string", "format": "date" }
                    }
                }
            }
        }));
        let a = serde_json::json!({
            "body": content("The body."),
            "note": content("The note."),
            "issued": "2026-01-02",
            "extra": { "x": 1, "y": 2 },
            "$cards": [ { "$kind": "note", "$body": content("Card body"), "on": "2027-03-04", "tag": "t" } ]
        });
        let b = serde_json::json!({
            "$cards": [ { "tag": "t", "on": "2027-03-04", "$body": content("Card body"), "$kind": "note" } ],
            "extra": { "y": 2, "x": 1 },
            "issued": "2026-01-02",
            "note": content("The note."),
            "body": content("The body.")
        });

        let (lib_a, win_a) = generate_lib_typ(&a, &meta).unwrap();
        let (lib_b, win_b) = generate_lib_typ(&b, &meta).unwrap();
        assert_eq!(lib_a, lib_b, "reordered input must emit identical source");
        let wa: Vec<_> = win_a.iter().map(|w| (&w.path, w.block.clone())).collect();
        let wb: Vec<_> = win_b.iter().map(|w| (&w.path, w.block.clone())).collect();
        assert_eq!(wa, wb, "windows must be identical too");
    }

    #[test]
    fn lit_serializes_the_json_value_model() {
        assert_eq!(lit(&serde_json::json!(null)), "none");
        assert_eq!(lit(&serde_json::json!(true)), "true");
        assert_eq!(lit(&serde_json::json!(42)), "42");
        assert_eq!(
            lit(&serde_json::json!(i64::MIN)),
            "(-9223372036854775807 - 1)"
        );
        assert_eq!(lit(&serde_json::json!(1.5)), "float(\"1.5\")");
        assert_eq!(lit(&serde_json::json!("hi")), "\"hi\"");
        assert_eq!(lit(&serde_json::json!([])), "()");
        assert_eq!(lit(&serde_json::json!([1])), "(1,)");
        assert_eq!(lit(&serde_json::json!({})), "(:)");
        assert_eq!(lit(&serde_json::json!({ "a": 1 })), "(\"a\": 1,)");
    }
}
